name: Jest

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }} tests
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install yarn
        run: npm ci
      - name: Run the tests
        run: npm run test
  windows-test:
    runs-on: "windows-latest"
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }} tests on Windows
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install yarn
        run: npm ci
      - name: Run the tests
        run: npm run test
