name: Type Checks

on:
  push:

jobs:
  typechecks:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install yarn
        run: npm ci
      - name: Check Linting
        run: npm run typechecks
